"use client";

/**
 * /admin/projects/[id]/auditor-handoff · Sesión 3B-2B.3 Phase X.4e NEW.
 *
 * Migrates magic-link generation UI from cross-cliente /admin/magic-links to
 * project-scoped auditor handoff. Per directive Marcos: magic links =
 * SOLO auditor ENAC flow at admin UI level. The other 32 non-auditor purposes
 * are AUTO-generated by workflow motors (M21 cliente onboarding, M05 firma
 * documentos, M07 evidencia intake, m_meetings actas approval, 1.D.E pentest
 * authorization, etc.) and never need manual Marcos generation.
 *
 * Scope: 3 auditor-related purposes only:
 *   - respuesta_requerimiento_auditor  (auditor asks specific info from cliente)
 *   - descarga_dossier_final           (auditor downloads handoff pack)
 *   - revisar_informe_verificacion     (auditor reviews tech verification)
 *
 * Other 32 purposes invisible from this page (auto-generated · motor-driven).
 *
 * Backend M12 motor unchanged · same generate + history endpoints reused.
 * MagicLinkGenerator component reused (Marcos picks auditor purpose from list).
 * Project context surfaced in header so Marcos knows which proyecto context.
 */
import { useQuery } from "@tanstack/react-query";
import Link from "next/link";
import { use } from "react";
import { ChevronLeft, ScrollText } from "lucide-react";

import { Skeleton } from "@/components/ui/skeleton";
import {
  Tabs,
  TabsContent,
  TabsList,
  TabsTrigger,
} from "@/components/ui/tabs";
import { MagicLinkGenerator } from "@/components/magic-links/MagicLinkGenerator";
import { MagicLinkHistoryTable } from "@/components/magic-links/MagicLinkHistoryTable";

import { api } from "@/lib/api";

interface ProjectHeaderResponse {
  project: { id: string; nombre: string };
  cliente: { id: string; nombre: string; cif: string };
}

export default function AdminProjectAuditorHandoffPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id: projectId } = use(params);

  const headerQ = useQuery<ProjectHeaderResponse>({
    queryKey: ["project-composer", "header", projectId],
    queryFn: () => api<ProjectHeaderResponse>(`/api/v1/projects/${projectId}/header`),
    staleTime: 60_000,
  });

  if (headerQ.isLoading || !headerQ.data) {
    return (
      <div className="flex flex-col gap-4">
        <Skeleton className="h-10 w-48" />
        <Skeleton className="h-12 w-full" />
        <Skeleton className="h-64 w-full" />
      </div>
    );
  }

  const project = headerQ.data.project;
  const cliente = headerQ.data.cliente;

  return (
    <div className="flex flex-col gap-6">
      <Link
        href={`/admin/projects/${projectId}/summary`}
        className="inline-flex w-fit items-center gap-1 text-sm font-bold text-fulkro-primary-700 hover:underline"
      >
        <ChevronLeft className="h-4 w-4" /> Volver al proyecto
      </Link>

      <header className="flex flex-col gap-2">
        <div className="flex items-center gap-3">
          <ScrollText className="h-7 w-7 text-fulkro-primary-700" />
          <h1 className="text-3xl font-bold text-[color:var(--fulkro-title)] tracking-tight">
            Entrega al auditor
          </h1>
        </div>
        <p className="text-base font-medium text-fulkro-ink-700">
          Genera enlaces seguros para que el auditor ENAC acceda al dossier
          final, entre al portal interactivo o responda requerimientos para{" "}
          <strong>{cliente.nombre}</strong> · proyecto{" "}
          <strong>{project.nombre}</strong>.
        </p>
        <p className="text-sm text-fulkro-ink-700">
          Pre-rellena <code className="font-mono">project_id</code>{" "}
          <code className="font-mono text-xs">{project.id}</code> y{" "}
          <code className="font-mono">client_id</code>{" "}
          <code className="font-mono text-xs">{cliente.id}</code> en el
          formulario. Selecciona uno de los 4 propósitos auditor:
        </p>
        <ul className="ml-4 list-disc text-sm text-fulkro-ink-700">
          <li>
            <strong>descarga_dossier_final</strong> · auditor descarga el
            ZIP firmado Ed25519 (entrega ENAC oficial · valida offline)
          </li>
          <li>
            <strong>auditor_portal_enac</strong> · auditor entra al portal
            interactivo (Sesión 3B-2B.6 CLUSTER 2 · 9 read-only views:
            resumen · DdA · MAGERIT · plan · evidencias · E-041 · audit log
            · pentest · documentos)
          </li>
          <li>
            <strong>respuesta_requerimiento_auditor</strong> · auditor pide
            información puntual al cliente
          </li>
          <li>
            <strong>revisar_informe_verificacion</strong> · auditor revisa
            informe de verificación técnica
          </li>
        </ul>
        <p className="text-xs text-fulkro-ink-700">
          El resto de los enlaces (firma · evidencia · onboarding · etc.) se
          generan automáticamente por los motores (M05/M07/M21/m_meetings/...) ·
          NO se manipulan desde aquí.
        </p>
      </header>

      <Tabs defaultValue="generate">
        <TabsList>
          <TabsTrigger value="generate">Generar enlace auditor</TabsTrigger>
          <TabsTrigger value="history">Histórico enlaces</TabsTrigger>
        </TabsList>
        <TabsContent value="generate" className="mt-6">
          <MagicLinkGenerator />
        </TabsContent>
        <TabsContent value="history" className="mt-6">
          <MagicLinkHistoryTable />
        </TabsContent>
      </Tabs>
    </div>
  );
}
