/**
 * P2 05 · /admin/projects/[id]/auditor-handoff · NEW (Sesión 3B-2B.3 Phase X.4e).
 *
 * Migrated from /admin/magic-links cross-cliente (now redirect). Project-scoped
 * auditor magic-link generation · 3 purposes only (R23 strict). Other 32
 * magic-link purposes auto-generated by motors (no UI surface).
 *
 * Renumbered from former p2/05_admin_clients.spec.ts (deleted Phase X.5).
 */
import { test } from "../_helpers/polish-test-fixture";
import { runProjectScopedProbe } from "../_helpers/spec-template";

test.describe("P2 · /admin/projects/[id]/auditor-handoff", () => {
  test("12-criteria empirical sweep", async ({ authedPage }, testInfo) => {
    await runProjectScopedProbe(authedPage, testInfo, {
      subPath: "auditor-handoff",
      pageName: "admin-project-auditor-handoff",
    });
  });
});
