"""PDF signature embed helper · Ejecutable 7.7 · TIER 1 canvas signature page.

Reusable function that appends a "Firma del cliente" block (canvas image +
nombre + apellido + fecha + IP + Ed25519 verification badge) at the end of
any PDF generated by Fulkro (propuesta_pdf · draft_audit_report ·
simulacro_pre_enac · acompañamiento certificates · etc).

Inputs:
- pdf_canvas (reportlab Canvas) OR builder pattern callable
- SigningEvent ORM instance (post-sign_canvas) with:
  · signature_canvas_dataurl (base64 PNG)
  · signed_name + signed_surname
  · signature_ed25519 (bytes)
  · event_hash_sha256 (str)
  · ip_address (optional)
  · created_at (datetime UTC)

Output: appends a new page at end of pdf canvas with signature block.

Doctrine sostained:
- ADR-009 firma electrónica simple eIDAS Art. 25.1 (NO eIDAS qualified)
- R6 hash chain inviolable preserved (signature_hex 8chars badge displayed)
- OPS-026 DRY (reuse reportlab platypus existing infrastructure)
"""
from __future__ import annotations

import base64
import io
from datetime import datetime
from typing import Optional

from reportlab.lib.colors import HexColor, white
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.lib.utils import ImageReader
from reportlab.pdfgen.canvas import Canvas

from backend.app.fulkro_identity import FULKRO_FOOTER_TEXT


def _parse_dataurl_to_image_bytes(dataurl: str) -> Optional[bytes]:
    """Decode 'data:image/png;base64,...' to raw PNG bytes."""
    if not dataurl or "base64," not in dataurl:
        return None
    try:
        _, b64 = dataurl.split("base64,", 1)
        return base64.b64decode(b64)
    except (ValueError, base64.binascii.Error):
        return None


def append_signature_page(
    pdf_canvas: Canvas,
    *,
    signature_canvas_dataurl: str,
    signed_name: str,
    signed_surname: str,
    signed_at: datetime,
    ip_address: Optional[str],
    signature_ed25519: bytes,
    event_hash_sha256: str,
    document_label: str,
    page_size: tuple[float, float] = A4,
) -> None:
    """Append a new page at end of pdf with signature block.

    Caller responsibility: invoke pdf_canvas.save() after this returns.

    The signature image is rendered at 6cm width centered. If the dataurl
    is invalid or empty, a placeholder note appears instead (graceful
    degradation per OPS-049 honest path).
    """
    width, height = page_size
    pdf_canvas.showPage()

    # ════════════════════════════════════════════════════════════════════
    # Header
    # ════════════════════════════════════════════════════════════════════
    pdf_canvas.setFillColor(HexColor("#7c3aed"))  # Fulkro violet
    pdf_canvas.rect(0, height - 2.5 * cm, width, 2.5 * cm, fill=1, stroke=0)
    pdf_canvas.setFillColor(white)
    pdf_canvas.setFont("Helvetica-Bold", 18)
    pdf_canvas.drawString(2 * cm, height - 1.6 * cm, "Firma del cliente")
    pdf_canvas.setFont("Helvetica", 10)
    pdf_canvas.drawString(
        2 * cm, height - 2.1 * cm,
        "Firma electrónica simple · eIDAS Art. 25.1 · Ed25519 + hash chain",
    )

    # ════════════════════════════════════════════════════════════════════
    # Document label
    # ════════════════════════════════════════════════════════════════════
    y = height - 3.5 * cm
    pdf_canvas.setFillColor(HexColor("#334155"))
    pdf_canvas.setFont("Helvetica-Bold", 12)
    pdf_canvas.drawString(2 * cm, y, "Documento firmado:")
    pdf_canvas.setFont("Helvetica", 11)
    pdf_canvas.drawString(6.5 * cm, y, document_label[:80])

    # ════════════════════════════════════════════════════════════════════
    # Signature image (canvas dataurl rendered centered ~6cm)
    # ════════════════════════════════════════════════════════════════════
    y -= 1.5 * cm
    pdf_canvas.setFont("Helvetica-Bold", 11)
    pdf_canvas.drawString(2 * cm, y, "Firma manuscrita:")

    image_bytes = _parse_dataurl_to_image_bytes(signature_canvas_dataurl)
    box_x = 2 * cm
    box_y = y - 5.5 * cm
    box_w = 8 * cm
    box_h = 4.5 * cm
    pdf_canvas.setStrokeColor(HexColor("#cbd5e1"))
    pdf_canvas.setLineWidth(1)
    pdf_canvas.rect(box_x, box_y, box_w, box_h, fill=0, stroke=1)

    if image_bytes:
        try:
            img = ImageReader(io.BytesIO(image_bytes))
            pdf_canvas.drawImage(
                img,
                box_x + 0.2 * cm, box_y + 0.2 * cm,
                width=box_w - 0.4 * cm,
                height=box_h - 0.4 * cm,
                preserveAspectRatio=True, anchor="c", mask="auto",
            )
        except Exception:
            # Graceful degradation (OPS-049) · render placeholder text
            pdf_canvas.setFillColor(HexColor("#64748b"))
            pdf_canvas.setFont("Helvetica-Oblique", 10)
            pdf_canvas.drawCentredString(
                box_x + box_w / 2, box_y + box_h / 2,
                "(firma capturada · imagen no renderizable)",
            )
    else:
        pdf_canvas.setFillColor(HexColor("#64748b"))
        pdf_canvas.setFont("Helvetica-Oblique", 10)
        pdf_canvas.drawCentredString(
            box_x + box_w / 2, box_y + box_h / 2,
            "(firma no disponible · render fallback)",
        )

    # ════════════════════════════════════════════════════════════════════
    # Cliente info (nombre + apellido + fecha + IP)
    # ════════════════════════════════════════════════════════════════════
    info_x = box_x + box_w + 1 * cm
    info_y = box_y + box_h - 0.5 * cm
    pdf_canvas.setFillColor(HexColor("#334155"))
    pdf_canvas.setFont("Helvetica-Bold", 10)
    pdf_canvas.drawString(info_x, info_y, "Nombre y apellido:")
    pdf_canvas.setFont("Helvetica", 10)
    pdf_canvas.drawString(
        info_x, info_y - 0.5 * cm,
        f"{signed_name} {signed_surname}"[:50],
    )

    pdf_canvas.setFont("Helvetica-Bold", 10)
    pdf_canvas.drawString(info_x, info_y - 1.4 * cm, "Fecha y hora:")
    pdf_canvas.setFont("Helvetica", 10)
    pdf_canvas.drawString(
        info_x, info_y - 1.9 * cm,
        signed_at.strftime("%Y-%m-%d %H:%M:%S UTC"),
    )

    pdf_canvas.setFont("Helvetica-Bold", 10)
    pdf_canvas.drawString(info_x, info_y - 2.8 * cm, "IP firmante:")
    pdf_canvas.setFont("Helvetica", 10)
    pdf_canvas.drawString(
        info_x, info_y - 3.3 * cm,
        ip_address or "no registrada",
    )

    # ════════════════════════════════════════════════════════════════════
    # Verification badge (Ed25519 signature hex 8chars + event hash chain)
    # ════════════════════════════════════════════════════════════════════
    badge_y = box_y - 1.5 * cm
    pdf_canvas.setFillColor(HexColor("#ecfdf5"))  # emerald-50
    pdf_canvas.setStrokeColor(HexColor("#10b981"))  # emerald-500
    pdf_canvas.setLineWidth(1.5)
    pdf_canvas.roundRect(
        2 * cm, badge_y - 1.7 * cm, width - 4 * cm, 1.7 * cm,
        radius=4, fill=1, stroke=1,
    )
    pdf_canvas.setFillColor(HexColor("#065f46"))  # emerald-900
    pdf_canvas.setFont("Helvetica-Bold", 11)
    pdf_canvas.drawString(
        2.4 * cm, badge_y - 0.6 * cm,
        "Firma electrónica verificada",
    )
    pdf_canvas.setFont("Helvetica", 9)
    sig_hex = signature_ed25519.hex()[:16] if signature_ed25519 else "n/a"
    chain_hex = event_hash_sha256[:16] if event_hash_sha256 else "n/a"
    pdf_canvas.drawString(
        2.4 * cm, badge_y - 1.1 * cm,
        f"Ed25519 system signature: {sig_hex}…",
    )
    pdf_canvas.drawString(
        2.4 * cm, badge_y - 1.5 * cm,
        f"Hash chain audit: {chain_hex}…",
    )

    # ════════════════════════════════════════════════════════════════════
    # Footer Fulkro identity (Ejecutable 7.6 reuse · OPS-026 DRY)
    # ════════════════════════════════════════════════════════════════════
    pdf_canvas.setFillColor(HexColor("#94a3b8"))
    pdf_canvas.setFont("Helvetica", 7)
    pdf_canvas.drawCentredString(
        width / 2, 1 * cm, FULKRO_FOOTER_TEXT,
    )
