"""Create RLS policies for all tables with client_id or project_id.

Run against the FULKRO database to enable tenant isolation.
Per v2.1 Parte 4.3: RLS on all tables with project_id or client_id.
"""
import pathlib

# Tables with their isolation column
# Priority: project_id if available (more granular), client_id as fallback
TABLES_PROJECT_ID = [
    "audit_sessions", "changes", "collaborative_workspaces",
    "committee_meetings", "controls", "dda_entries",
    "discovered_assets", "discovered_identities", "documents",
    "evidence", "findings", "incidents", "magic_links",
    "nominations", "obligations", "onboarding_sessions",
    "pentest_runs", "procedures", "project_exports",
    "project_lifecycle_states", "project_plans", "project_risks",
    "status_reports", "systems", "training_records", "vendors",
    "vulnerabilities",
]

TABLES_CLIENT_ID = [
    "client_dashboard_state", "client_workspaces",
    "invoices", "projects", "retainer_contracts",
]

# Tables with both - use project_id as primary isolation
TABLES_BOTH = [
    "archived_projects",  # has both client_id and project_id
]


def generate_sql() -> str:
    lines = [
        "-- RLS Policies for FULKRO tenant isolation",
        "-- Generated by scripts/create_rls_policies.py",
        "-- Per v2.1 Parte 4.3: RLS on all tables with client_id or project_id",
        "",
    ]

    # Project-level isolation
    for table in TABLES_PROJECT_ID:
        lines.extend([
            f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;",
            f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY;",
            f"DROP POLICY IF EXISTS project_isolation ON {table};",
            f"CREATE POLICY project_isolation ON {table}",
            f"  USING (project_id = current_project_id());",
            "",
        ])

    # Client-level isolation
    for table in TABLES_CLIENT_ID:
        lines.extend([
            f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;",
            f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY;",
            f"DROP POLICY IF EXISTS client_isolation ON {table};",
            f"CREATE POLICY client_isolation ON {table}",
            f"  USING (client_id = current_client_id());",
            "",
        ])

    # Tables with both columns - dual policy
    for table in TABLES_BOTH:
        lines.extend([
            f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;",
            f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY;",
            f"DROP POLICY IF EXISTS project_isolation ON {table};",
            f"CREATE POLICY project_isolation ON {table}",
            f"  USING (project_id = current_project_id());",
            "",
        ])

    # Superuser bypass - the fulkro role needs to bypass RLS for admin operations
    # In production, the app will SET LOCAL before each request
    lines.extend([
        "-- Grant the fulkro role ability to bypass RLS when needed",
        "-- The app sets current_client_id/current_project_id per request",
        "-- Without setting these, queries return nothing (safe default)",
        "",
        "-- Create a BYPASSRLS role for admin/migration operations",
        "ALTER ROLE fulkro BYPASSRLS;",
        "",
    ])

    return "\n".join(lines)


if __name__ == "__main__":
    sql = generate_sql()
    out = pathlib.Path("/root/fulkro/scripts/rls_policies.sql")
    out.write_text(sql)
    print(f"Generated {sql.count('CREATE POLICY')} policies")
    print(f"Written to {out}")
