-- RLS Policies for FULKRO tenant isolation
-- Generated by scripts/create_rls_policies.py
-- Per v2.1 Parte 4.3: RLS on all tables with client_id or project_id

ALTER TABLE audit_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_sessions FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS project_isolation ON audit_sessions;
CREATE POLICY project_isolation ON audit_sessions
  USING (project_id = current_project_id());

ALTER TABLE changes ENABLE ROW LEVEL SECURITY;
ALTER TABLE changes FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS project_isolation ON changes;
CREATE POLICY project_isolation ON changes
  USING (project_id = current_project_id());

ALTER TABLE collaborative_workspaces ENABLE ROW LEVEL SECURITY;
ALTER TABLE collaborative_workspaces FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS project_isolation ON collaborative_workspaces;
CREATE POLICY project_isolation ON collaborative_workspaces
  USING (project_id = current_project_id());

ALTER TABLE committee_meetings ENABLE ROW LEVEL SECURITY;
ALTER TABLE committee_meetings FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS project_isolation ON committee_meetings;
CREATE POLICY project_isolation ON committee_meetings
  USING (project_id = current_project_id());

ALTER TABLE controls ENABLE ROW LEVEL SECURITY;
ALTER TABLE controls FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS project_isolation ON controls;
CREATE POLICY project_isolation ON controls
  USING (project_id = current_project_id());

ALTER TABLE dda_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE dda_entries FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS project_isolation ON dda_entries;
CREATE POLICY project_isolation ON dda_entries
  USING (project_id = current_project_id());

ALTER TABLE discovered_assets ENABLE ROW LEVEL SECURITY;
ALTER TABLE discovered_assets FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS project_isolation ON discovered_assets;
CREATE POLICY project_isolation ON discovered_assets
  USING (project_id = current_project_id());

ALTER TABLE discovered_identities ENABLE ROW LEVEL SECURITY;
ALTER TABLE discovered_identities FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS project_isolation ON discovered_identities;
CREATE POLICY project_isolation ON discovered_identities
  USING (project_id = current_project_id());

ALTER TABLE documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE documents FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS project_isolation ON documents;
CREATE POLICY project_isolation ON documents
  USING (project_id = current_project_id());

ALTER TABLE evidence ENABLE ROW LEVEL SECURITY;
ALTER TABLE evidence FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS project_isolation ON evidence;
CREATE POLICY project_isolation ON evidence
  USING (project_id = current_project_id());

ALTER TABLE findings ENABLE ROW LEVEL SECURITY;
ALTER TABLE findings FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS project_isolation ON findings;
CREATE POLICY project_isolation ON findings
  USING (project_id = current_project_id());

ALTER TABLE incidents ENABLE ROW LEVEL SECURITY;
ALTER TABLE incidents FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS project_isolation ON incidents;
CREATE POLICY project_isolation ON incidents
  USING (project_id = current_project_id());

ALTER TABLE magic_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE magic_links FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS project_isolation ON magic_links;
CREATE POLICY project_isolation ON magic_links
  USING (project_id = current_project_id());

ALTER TABLE nominations ENABLE ROW LEVEL SECURITY;
ALTER TABLE nominations FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS project_isolation ON nominations;
CREATE POLICY project_isolation ON nominations
  USING (project_id = current_project_id());

ALTER TABLE obligations ENABLE ROW LEVEL SECURITY;
ALTER TABLE obligations FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS project_isolation ON obligations;
CREATE POLICY project_isolation ON obligations
  USING (project_id = current_project_id());

ALTER TABLE onboarding_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE onboarding_sessions FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS project_isolation ON onboarding_sessions;
CREATE POLICY project_isolation ON onboarding_sessions
  USING (project_id = current_project_id());

ALTER TABLE pentest_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE pentest_runs FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS project_isolation ON pentest_runs;
CREATE POLICY project_isolation ON pentest_runs
  USING (project_id = current_project_id());

ALTER TABLE procedures ENABLE ROW LEVEL SECURITY;
ALTER TABLE procedures FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS project_isolation ON procedures;
CREATE POLICY project_isolation ON procedures
  USING (project_id = current_project_id());

ALTER TABLE project_exports ENABLE ROW LEVEL SECURITY;
ALTER TABLE project_exports FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS project_isolation ON project_exports;
CREATE POLICY project_isolation ON project_exports
  USING (project_id = current_project_id());

ALTER TABLE project_lifecycle_states ENABLE ROW LEVEL SECURITY;
ALTER TABLE project_lifecycle_states FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS project_isolation ON project_lifecycle_states;
CREATE POLICY project_isolation ON project_lifecycle_states
  USING (project_id = current_project_id());

ALTER TABLE project_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE project_plans FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS project_isolation ON project_plans;
CREATE POLICY project_isolation ON project_plans
  USING (project_id = current_project_id());

ALTER TABLE project_risks ENABLE ROW LEVEL SECURITY;
ALTER TABLE project_risks FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS project_isolation ON project_risks;
CREATE POLICY project_isolation ON project_risks
  USING (project_id = current_project_id());

ALTER TABLE status_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE status_reports FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS project_isolation ON status_reports;
CREATE POLICY project_isolation ON status_reports
  USING (project_id = current_project_id());

ALTER TABLE systems ENABLE ROW LEVEL SECURITY;
ALTER TABLE systems FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS project_isolation ON systems;
CREATE POLICY project_isolation ON systems
  USING (project_id = current_project_id());

ALTER TABLE training_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE training_records FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS project_isolation ON training_records;
CREATE POLICY project_isolation ON training_records
  USING (project_id = current_project_id());

ALTER TABLE vendors ENABLE ROW LEVEL SECURITY;
ALTER TABLE vendors FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS project_isolation ON vendors;
CREATE POLICY project_isolation ON vendors
  USING (project_id = current_project_id());

ALTER TABLE vulnerabilities ENABLE ROW LEVEL SECURITY;
ALTER TABLE vulnerabilities FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS project_isolation ON vulnerabilities;
CREATE POLICY project_isolation ON vulnerabilities
  USING (project_id = current_project_id());

ALTER TABLE client_dashboard_state ENABLE ROW LEVEL SECURITY;
ALTER TABLE client_dashboard_state FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS client_isolation ON client_dashboard_state;
CREATE POLICY client_isolation ON client_dashboard_state
  USING (client_id = current_client_id());

ALTER TABLE client_workspaces ENABLE ROW LEVEL SECURITY;
ALTER TABLE client_workspaces FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS client_isolation ON client_workspaces;
CREATE POLICY client_isolation ON client_workspaces
  USING (client_id = current_client_id());

ALTER TABLE invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE invoices FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS client_isolation ON invoices;
CREATE POLICY client_isolation ON invoices
  USING (client_id = current_client_id());

ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE projects FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS client_isolation ON projects;
CREATE POLICY client_isolation ON projects
  USING (client_id = current_client_id());

ALTER TABLE retainer_contracts ENABLE ROW LEVEL SECURITY;
ALTER TABLE retainer_contracts FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS client_isolation ON retainer_contracts;
CREATE POLICY client_isolation ON retainer_contracts
  USING (client_id = current_client_id());

ALTER TABLE archived_projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE archived_projects FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS project_isolation ON archived_projects;
CREATE POLICY project_isolation ON archived_projects
  USING (project_id = current_project_id());

-- Grant the fulkro role ability to bypass RLS when needed
-- The app sets current_client_id/current_project_id per request
-- Without setting these, queries return nothing (safe default)

-- Create a BYPASSRLS role for admin/migration operations
ALTER ROLE fulkro BYPASSRLS;
