"""m6_add_placeholders_detected_to_templates

Revision ID: 10e0be09d799
Revises: 3072261bdbf0
Create Date: 2026-04-14 22:11:55.223071
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '10e0be09d799'
down_revision: Union[str, None] = '3072261bdbf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('placeholders_detected', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('templates', 'placeholders_detected')
    # ### end Alembic commands ###
