"""m6_create_templates_add_columns_to_documents

Revision ID: 3072261bdbf0
Revises: 4fe29eda5fdd
Create Date: 2026-04-14 18:06:23.064931
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '3072261bdbf0'
down_revision: Union[str, None] = '4fe29eda5fdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('codigo', sa.String(length=32), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('categoria', sa.String(length=32), nullable=False),
    sa.Column('familia_ens', sa.String(length=32), nullable=True),
    sa.Column('aplica_desde', sa.String(length=16), nullable=True),
    sa.Column('version_actual', sa.String(length=16), nullable=False),
    sa.Column('docx_path', sa.String(length=512), nullable=True),
    sa.Column('placeholders_requeridos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('fuente_md', sa.String(length=512), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.add_column('documents', sa.Column('template_codigo', sa.String(length=32), nullable=True))
    op.add_column('documents', sa.Column('docx_path', sa.String(length=512), nullable=True))
    op.add_column('documents', sa.Column('pdf_path', sa.String(length=512), nullable=True))
    op.add_column('documents', sa.Column('rendered_hash', sa.String(length=64), nullable=True))
    op.add_column('documents', sa.Column('signature_ed25519', sa.String(length=128), nullable=True))
    op.add_column('documents', sa.Column('context_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('documents', sa.Column('generated_by', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('generated_at', postgresql.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'generated_at')
    op.drop_column('documents', 'generated_by')
    op.drop_column('documents', 'context_snapshot')
    op.drop_column('documents', 'signature_ed25519')
    op.drop_column('documents', 'rendered_hash')
    op.drop_column('documents', 'pdf_path')
    op.drop_column('documents', 'docx_path')
    op.drop_column('documents', 'template_codigo')
    op.drop_table('templates')
    # ### end Alembic commands ###
