"""m19_add_materialization_and_closure_evidence_to_project_risks

Revision ID: 4cf0463a1720
Revises: 0505cf3174f8
Create Date: 2026-04-14 14:09:28.324819
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '4cf0463a1720'
down_revision: Union[str, None] = '0505cf3174f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_risks', sa.Column('materialization_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('project_risks', sa.Column('closure_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_risks', 'closure_evidence')
    op.drop_column('project_risks', 'materialization_evidence')
    # ### end Alembic commands ###
