"""m4_add_metadata_jsonb_to_findings

Revision ID: 4fe29eda5fdd
Revises: 4cf0463a1720
Create Date: 2026-04-14 15:20:07.675967
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '4fe29eda5fdd'
down_revision: Union[str, None] = '4cf0463a1720'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('findings', sa.Column('metadata_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('findings', 'metadata_jsonb')
    # ### end Alembic commands ###
