"""m05: extend obligations table for Motor 5

Revision ID: 5562bddd5873
Revises: 5cf3ce7cbea9
Create Date: 2026-04-15 14:26:01.067501
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '5562bddd5873'
down_revision: Union[str, None] = '5cf3ce7cbea9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('obligations', sa.Column('template_id', sa.String(length=80), nullable=True))
    op.add_column('obligations', sa.Column('template_version', sa.String(length=20), nullable=True))
    op.add_column('obligations', sa.Column('measure_code', sa.String(length=40), nullable=True))
    op.add_column('obligations', sa.Column('titulo', sa.String(length=200), nullable=True))
    op.add_column('obligations', sa.Column('entregable_tipo', sa.String(length=40), nullable=True))
    op.add_column('obligations', sa.Column('magic_link_template', sa.String(length=60), nullable=True))
    op.add_column('obligations', sa.Column('fecha_completado', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('obligations', sa.Column('dependencias_template_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('obligations', sa.Column('criterios_aceptacion', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('obligations', sa.Column('fuente_normativa', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('obligations', sa.Column('metadata_extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_obligations_measure_code'), 'obligations', ['measure_code'], unique=False)
    op.create_index(op.f('ix_obligations_template_id'), 'obligations', ['template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_obligations_template_id'), table_name='obligations')
    op.drop_index(op.f('ix_obligations_measure_code'), table_name='obligations')
    op.drop_column('obligations', 'metadata_extra')
    op.drop_column('obligations', 'fuente_normativa')
    op.drop_column('obligations', 'criterios_aceptacion')
    op.drop_column('obligations', 'dependencias_template_ids')
    op.drop_column('obligations', 'fecha_completado')
    op.drop_column('obligations', 'magic_link_template')
    op.drop_column('obligations', 'entregable_tipo')
    op.drop_column('obligations', 'titulo')
    op.drop_column('obligations', 'measure_code')
    op.drop_column('obligations', 'template_version')
    op.drop_column('obligations', 'template_id')
    # ### end Alembic commands ###
