"""m07_add_evidence_extension_columns

Revision ID: 67c0ce2f126f
Revises: 5562bddd5873
Create Date: 2026-04-15 17:53:11.518676
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '67c0ce2f126f'
down_revision: Union[str, None] = '5562bddd5873'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evidence', sa.Column('evidence_type_id', sa.String(length=80), nullable=True))
    op.add_column('evidence', sa.Column('nombre_tipo', sa.String(length=120), nullable=True))
    op.add_column('evidence', sa.Column('fichero_nombre_original', sa.String(length=255), nullable=True))
    op.add_column('evidence', sa.Column('fichero_mime_type', sa.String(length=100), nullable=True))
    op.add_column('evidence', sa.Column('fichero_tamano_bytes', sa.Integer(), nullable=True))
    op.add_column('evidence', sa.Column('firma_payload_sha256', sa.String(length=64), nullable=True))
    op.add_column('evidence', sa.Column('measure_code', sa.String(length=40), nullable=True))
    op.add_column('evidence', sa.Column('obligation_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_evidence_evidence_type_id'), 'evidence', ['evidence_type_id'], unique=False)
    op.create_index(op.f('ix_evidence_measure_code'), 'evidence', ['measure_code'], unique=False)
    op.create_index(op.f('ix_evidence_obligation_id'), 'evidence', ['obligation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_obligation_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_measure_code'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_evidence_type_id'), table_name='evidence')
    op.drop_column('evidence', 'obligation_id')
    op.drop_column('evidence', 'measure_code')
    op.drop_column('evidence', 'firma_payload_sha256')
    op.drop_column('evidence', 'fichero_tamano_bytes')
    op.drop_column('evidence', 'fichero_mime_type')
    op.drop_column('evidence', 'fichero_nombre_original')
    op.drop_column('evidence', 'nombre_tipo')
    op.drop_column('evidence', 'evidence_type_id')
    # ### end Alembic commands ###
