"""corpus: add knowledge extensions + ens extensions + llm log

Revision ID: 80bebdb183fd
Revises: 10e0be09d799
Create Date: 2026-04-15 02:29:20.010225
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '80bebdb183fd'
down_revision: Union[str, None] = '10e0be09d799'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ens_measure_dimensiones',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('measure_code', sa.String(length=32), nullable=False),
    sa.Column('refuerzo_level', sa.String(length=16), nullable=True),
    sa.Column('dimension', sa.String(length=1), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('measure_code', 'refuerzo_level', 'dimension', name='uq_ens_dimension_code_level_dim')
    )
    op.create_index(op.f('ix_ens_measure_dimensiones_measure_code'), 'ens_measure_dimensiones', ['measure_code'], unique=False)
    op.create_table('ens_measure_evidencia_types',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('measure_code', sa.String(length=32), nullable=False),
    sa.Column('evidence_type', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('freshness_days', sa.Integer(), nullable=True),
    sa.Column('applicable_categories', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('measure_code', 'evidence_type', name='uq_ens_evidencia_code_type')
    )
    op.create_index(op.f('ix_ens_measure_evidencia_types_measure_code'), 'ens_measure_evidencia_types', ['measure_code'], unique=False)
    op.create_table('knowledge_sources',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('publisher', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=True),
    sa.Column('publication_date', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('language', sa.String(length=8), server_default=sa.text("'es'"), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('llm_interaction_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('feature', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('prompt_hash', sa.String(length=64), nullable=False),
    sa.Column('prompt_preview', sa.Text(), nullable=True),
    sa.Column('response_preview', sa.Text(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'success'"), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_interaction_log_created_at'), 'llm_interaction_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_llm_interaction_log_feature'), 'llm_interaction_log', ['feature'], unique=False)
    op.create_index(op.f('ix_llm_interaction_log_project_id'), 'llm_interaction_log', ['project_id'], unique=False)
    op.create_index(op.f('ix_llm_interaction_log_prompt_hash'), 'llm_interaction_log', ['prompt_hash'], unique=False)
    op.create_index(op.f('ix_llm_interaction_log_status'), 'llm_interaction_log', ['status'], unique=False)
    op.create_index(op.f('ix_llm_interaction_log_tenant_id'), 'llm_interaction_log', ['tenant_id'], unique=False)
    op.create_table('ens_measure_guias_ccn',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('measure_code', sa.String(length=32), nullable=False),
    sa.Column('guia_code', sa.String(length=32), nullable=False),
    sa.Column('section_ref', sa.String(length=64), nullable=True),
    sa.Column('chunk_id', sa.UUID(), nullable=True),
    sa.Column('relevance', sa.String(length=32), server_default=sa.text("'develops'"), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['knowledge_chunks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('measure_code', 'guia_code', 'section_ref', name='uq_ens_guia_code_guia_section')
    )
    op.create_index(op.f('ix_ens_measure_guias_ccn_guia_code'), 'ens_measure_guias_ccn', ['guia_code'], unique=False)
    op.create_index(op.f('ix_ens_measure_guias_ccn_measure_code'), 'ens_measure_guias_ccn', ['measure_code'], unique=False)
    op.create_table('ens_measure_refuerzos',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('measure_code', sa.String(length=32), nullable=False),
    sa.Column('refuerzo_level', sa.String(length=16), nullable=False),
    sa.Column('applicable_categories', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_chunk_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_chunk_id'], ['knowledge_chunks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('measure_code', 'refuerzo_level', name='uq_ens_refuerzo_code_level')
    )
    op.create_index(op.f('ix_ens_measure_refuerzos_measure_code'), 'ens_measure_refuerzos', ['measure_code'], unique=False)
    op.create_table('knowledge_links',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_chunk_id', sa.UUID(), nullable=False),
    sa.Column('target_chunk_id', sa.UUID(), nullable=False),
    sa.Column('link_type', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_chunk_id'], ['knowledge_chunks.id'], ),
    sa.ForeignKeyConstraint(['target_chunk_id'], ['knowledge_chunks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_chunk_id', 'target_chunk_id', 'link_type', name='uq_knowledge_links_src_tgt_type')
    )
    op.add_column('knowledge_chunks', sa.Column('chunk_index', sa.Integer(), nullable=True))
    op.add_column('knowledge_chunks', sa.Column('heading_path', sa.String(length=512), nullable=True))
    op.add_column('knowledge_chunks', sa.Column('measure_code', sa.String(length=32), nullable=True))
    op.add_column('knowledge_chunks', sa.Column('article_ref', sa.String(length=64), nullable=True))
    op.add_column('knowledge_chunks', sa.Column('content', sa.Text(), nullable=True))
    op.add_column('knowledge_chunks', sa.Column('token_count', sa.Integer(), nullable=True))
    op.execute(
        "ALTER TABLE knowledge_chunks ADD COLUMN IF NOT EXISTS content_tsvector tsvector "
        "GENERATED ALWAYS AS (to_tsvector('spanish', coalesce(contenido, coalesce(content, '')))) STORED"
    )
    op.create_index('ix_knowledge_chunks_embedding_hnsw', 'knowledge_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': 16, 'ef_construction': 64})
    op.create_index(op.f('ix_knowledge_chunks_measure_code'), 'knowledge_chunks', ['measure_code'], unique=False)
    op.create_index('ix_knowledge_chunks_tsvector', 'knowledge_chunks', ['content_tsvector'], unique=False, postgresql_using='gin')
    op.add_column('knowledge_documents', sa.Column('source_id', sa.UUID(), nullable=True))
    op.add_column('knowledge_documents', sa.Column('title', sa.String(length=512), nullable=True))
    op.add_column('knowledge_documents', sa.Column('mime_type', sa.String(length=128), server_default=sa.text("'text/html'"), nullable=False))
    op.add_column('knowledge_documents', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.add_column('knowledge_documents', sa.Column('chunk_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('knowledge_documents', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_foreign_key(None, 'knowledge_documents', 'knowledge_sources', ['source_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'knowledge_documents', type_='foreignkey')
    op.drop_column('knowledge_documents', 'metadata')
    op.drop_column('knowledge_documents', 'chunk_count')
    op.drop_column('knowledge_documents', 'content_hash')
    op.drop_column('knowledge_documents', 'mime_type')
    op.drop_column('knowledge_documents', 'title')
    op.drop_column('knowledge_documents', 'source_id')
    op.drop_index('ix_knowledge_chunks_tsvector', table_name='knowledge_chunks', postgresql_using='gin')
    op.drop_index(op.f('ix_knowledge_chunks_measure_code'), table_name='knowledge_chunks')
    op.drop_index('ix_knowledge_chunks_embedding_hnsw', table_name='knowledge_chunks', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': 16, 'ef_construction': 64})
    op.drop_column('knowledge_chunks', 'content_tsvector')
    op.drop_column('knowledge_chunks', 'token_count')
    op.drop_column('knowledge_chunks', 'content')
    op.drop_column('knowledge_chunks', 'article_ref')
    op.drop_column('knowledge_chunks', 'measure_code')
    op.drop_column('knowledge_chunks', 'heading_path')
    op.drop_column('knowledge_chunks', 'chunk_index')
    op.drop_table('knowledge_links')
    op.drop_index(op.f('ix_ens_measure_refuerzos_measure_code'), table_name='ens_measure_refuerzos')
    op.drop_table('ens_measure_refuerzos')
    op.drop_index(op.f('ix_ens_measure_guias_ccn_measure_code'), table_name='ens_measure_guias_ccn')
    op.drop_index(op.f('ix_ens_measure_guias_ccn_guia_code'), table_name='ens_measure_guias_ccn')
    op.drop_table('ens_measure_guias_ccn')
    op.drop_index(op.f('ix_llm_interaction_log_tenant_id'), table_name='llm_interaction_log')
    op.drop_index(op.f('ix_llm_interaction_log_status'), table_name='llm_interaction_log')
    op.drop_index(op.f('ix_llm_interaction_log_prompt_hash'), table_name='llm_interaction_log')
    op.drop_index(op.f('ix_llm_interaction_log_project_id'), table_name='llm_interaction_log')
    op.drop_index(op.f('ix_llm_interaction_log_feature'), table_name='llm_interaction_log')
    op.drop_index(op.f('ix_llm_interaction_log_created_at'), table_name='llm_interaction_log')
    op.drop_table('llm_interaction_log')
    op.drop_table('knowledge_sources')
    op.drop_index(op.f('ix_ens_measure_evidencia_types_measure_code'), table_name='ens_measure_evidencia_types')
    op.drop_table('ens_measure_evidencia_types')
    op.drop_index(op.f('ix_ens_measure_dimensiones_measure_code'), table_name='ens_measure_dimensiones')
    op.drop_table('ens_measure_dimensiones')
    # ### end Alembic commands ###
