"""add MAGERIT core tables

Revision ID: af85d71528af
Revises: e41cd7163c02
Create Date: 2026-04-11 20:00:34.864524
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'af85d71528af'
down_revision: Union[str, None] = 'e41cd7163c02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('magerit_asset_types',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category_code', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_dimensions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('magerit_ens_mapping',
    sa.Column('ens_measure', sa.String(length=20), nullable=False),
    sa.Column('ens_measure_name', sa.String(length=255), nullable=True),
    sa.Column('magerit_safeguards', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('magerit_safeguards',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('family', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('protects_asset_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mitigates_threats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('efficacy_typical', sa.String(length=20), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('magerit_threats',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('group_code', sa.String(length=5), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('affected_asset_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('affected_dimensions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('typical_frequency', sa.String(length=20), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('magerit_analysis',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('approved_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('methodology_version', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('magerit_assets',
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('asset_type_code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('value_d', sa.Integer(), nullable=True),
    sa.Column('value_i', sa.Integer(), nullable=True),
    sa.Column('value_c', sa.Integer(), nullable=True),
    sa.Column('value_a', sa.Integer(), nullable=True),
    sa.Column('value_t', sa.Integer(), nullable=True),
    sa.Column('accumulated_d', sa.Integer(), nullable=True),
    sa.Column('accumulated_i', sa.Integer(), nullable=True),
    sa.Column('accumulated_c', sa.Integer(), nullable=True),
    sa.Column('accumulated_a', sa.Integer(), nullable=True),
    sa.Column('accumulated_t', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['magerit_analysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('magerit_safeguard_deployment',
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('safeguard_code', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('efficacy', sa.Integer(), nullable=False),
    sa.Column('effect_type', sa.String(length=20), nullable=False),
    sa.Column('responsible', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['magerit_analysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('magerit_asset_dependencies',
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('superior_asset_id', sa.UUID(), nullable=False),
    sa.Column('inferior_asset_id', sa.UUID(), nullable=False),
    sa.Column('dependency_degree', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['magerit_analysis.id'], ),
    sa.ForeignKeyConstraint(['inferior_asset_id'], ['magerit_assets.id'], ),
    sa.ForeignKeyConstraint(['superior_asset_id'], ['magerit_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('magerit_risk_calculation',
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('threat_code', sa.String(length=10), nullable=False),
    sa.Column('dimension', sa.String(length=1), nullable=False),
    sa.Column('impact_intrinsic', sa.Float(), nullable=True),
    sa.Column('risk_intrinsic_accumulated', sa.Float(), nullable=True),
    sa.Column('risk_intrinsic_repercuted', sa.Float(), nullable=True),
    sa.Column('impact_effective', sa.Float(), nullable=True),
    sa.Column('risk_effective', sa.Float(), nullable=True),
    sa.Column('risk_residual', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=5), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['magerit_analysis.id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['magerit_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('magerit_threat_assessment',
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('threat_code', sa.String(length=10), nullable=False),
    sa.Column('probability', sa.Integer(), nullable=False),
    sa.Column('degradation_d', sa.Integer(), nullable=True),
    sa.Column('degradation_i', sa.Integer(), nullable=True),
    sa.Column('degradation_c', sa.Integer(), nullable=True),
    sa.Column('degradation_a', sa.Integer(), nullable=True),
    sa.Column('degradation_t', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['magerit_analysis.id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['magerit_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('magerit_treatment_plan',
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('threat_code', sa.String(length=10), nullable=False),
    sa.Column('dimension', sa.String(length=1), nullable=False),
    sa.Column('current_risk_level', sa.String(length=5), nullable=False),
    sa.Column('current_risk_value', sa.Float(), nullable=True),
    sa.Column('treatment', sa.String(length=20), nullable=False),
    sa.Column('action_description', sa.Text(), nullable=True),
    sa.Column('proposed_safeguards', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_risk_level', sa.String(length=5), nullable=True),
    sa.Column('responsible', sa.String(length=255), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['magerit_analysis.id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['magerit_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('magerit_treatment_plan')
    op.drop_table('magerit_threat_assessment')
    op.drop_table('magerit_risk_calculation')
    op.drop_table('magerit_asset_dependencies')
    op.drop_table('magerit_safeguard_deployment')
    op.drop_table('magerit_assets')
    op.drop_table('magerit_analysis')
    op.drop_table('magerit_threats')
    op.drop_table('magerit_safeguards')
    op.drop_table('magerit_ens_mapping')
    op.drop_table('magerit_asset_types')
    # ### end Alembic commands ###
