"""add_evidence_renewal_requests_table

Revision ID: eb0a885d141a
Revises: 67c0ce2f126f
Create Date: 2026-04-15 18:33:33.691502
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'eb0a885d141a'
down_revision: Union[str, None] = '67c0ce2f126f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence_renewal_requests',
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('measure_code', sa.String(length=40), nullable=False),
    sa.Column('motivo', sa.String(length=80), nullable=False),
    sa.Column('estado', sa.String(length=40), nullable=False),
    sa.Column('fecha_caducidad_original', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('dias_para_caducar', sa.Integer(), nullable=True),
    sa.Column('new_evidence_id', sa.UUID(), nullable=True),
    sa.Column('metadata_renewal', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_renewal_requests_estado'), 'evidence_renewal_requests', ['estado'], unique=False)
    op.create_index(op.f('ix_evidence_renewal_requests_evidence_id'), 'evidence_renewal_requests', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_evidence_renewal_requests_measure_code'), 'evidence_renewal_requests', ['measure_code'], unique=False)
    op.create_index(op.f('ix_evidence_renewal_requests_project_id'), 'evidence_renewal_requests', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_renewal_requests_project_id'), table_name='evidence_renewal_requests')
    op.drop_index(op.f('ix_evidence_renewal_requests_measure_code'), table_name='evidence_renewal_requests')
    op.drop_index(op.f('ix_evidence_renewal_requests_evidence_id'), table_name='evidence_renewal_requests')
    op.drop_index(op.f('ix_evidence_renewal_requests_estado'), table_name='evidence_renewal_requests')
    op.drop_table('evidence_renewal_requests')
    # ### end Alembic commands ###
