"""SAN-E MB-9.bis mini-atom 3 · per-norma compliance reports table.

Stores periodic compliance reports per regulatory norma (RGPD, NIS2,
ISO 27001, ENS, LOPDGDD, LSSI-CE, AEPD Cookies). Generated by
``ComplianceNormaReportsService`` from the ``NormaRegistry`` plugins.

Revision ID: sane_mb9bis_norma_rep_001
Revises: sane_mb9bis_consent_001
Create Date: 2026-05-12
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


revision = "sane_mb9bis_norma_rep_001"
down_revision = "sane_mb9bis_consent_001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "fulkro_compliance_norma_reports",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("norma_key", sa.String(50), nullable=False),
        sa.Column("norma_name", sa.String(200), nullable=False),
        sa.Column("period_start", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("period_end", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("compliance_score", sa.Numeric(5, 2), nullable=False),
        sa.Column("status", sa.String(20), nullable=False),
        sa.Column("checks_total", sa.Integer, nullable=False, server_default="0"),
        sa.Column("checks_passed", sa.Integer, nullable=False, server_default="0"),
        sa.Column("checks_warning", sa.Integer, nullable=False, server_default="0"),
        sa.Column("checks_failed", sa.Integer, nullable=False, server_default="0"),
        sa.Column("report_md_content", sa.Text, nullable=False),
        sa.Column("report_json_content", postgresql.JSONB, nullable=False),
        sa.Column("storage_path_dev", sa.Text, nullable=True),
        sa.Column("storage_path_prod", sa.Text, nullable=True),
        sa.Column("email_sent_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "generated_at",
            postgresql.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
        sa.Column(
            "reviewed_by_marcos_at", postgresql.TIMESTAMP(timezone=True), nullable=True
        ),
        sa.Column("reviewed_marcos_notes", sa.Text, nullable=True),
        sa.CheckConstraint(
            "status IN ('green', 'yellow', 'red', 'unknown')",
            name="ck_norma_reports_status",
        ),
    )
    op.create_index(
        "ix_norma_reports_norma_period",
        "fulkro_compliance_norma_reports",
        ["norma_key", "period_end"],
    )
    op.create_index(
        "ix_norma_reports_compliance_score",
        "fulkro_compliance_norma_reports",
        ["compliance_score"],
    )
    op.execute(
        "GRANT SELECT, INSERT, UPDATE, DELETE ON fulkro_compliance_norma_reports "
        "TO fulkro_app"
    )


def downgrade() -> None:
    op.drop_index(
        "ix_norma_reports_compliance_score",
        table_name="fulkro_compliance_norma_reports",
    )
    op.drop_index(
        "ix_norma_reports_norma_period",
        table_name="fulkro_compliance_norma_reports",
    )
    op.drop_table("fulkro_compliance_norma_reports")
