/** Fixture de leads para dev/test (Playwright pipeline.spec.ts).
 *
 * Sólo MOCK_LEADS sobrevive: lo consume hooks/useLeads.ts como fallback
 * gated por NODE_ENV (R24: 0 mocks en producción). Los antiguos
 * MOCK_KPIS/MY_DAY/ALERTS/ACTIVITY se eliminaron (0 consumidores · el
 * dashboard real usa GET /api/v1/dashboard/* vía useDashboardData.ts).
 */
import type { Lead } from "./types";

const now = new Date("2026-04-20T10:00:00Z").toISOString();

export const MOCK_LEADS: Lead[] = [
  {
    id: "lead-1",
    empresa: "Ayuntamiento de Valencia",
    cif: "P4625200B",
    sector: "Sector público",
    score: 62,
    rag: "amber",
    value_eur: 8_500,
    stage: "new",
    contact_name: "María López",
    contact_email: "secretario@ayto-vlc.es",
    source: "licitación PLACSP",
    pliego_attached: true,
    last_touched_at: "2026-04-17T09:00:00Z",
  },
  {
    id: "lead-2",
    empresa: "DataForma Galicia",
    cif: "B36487129",
    sector: "Tecnología",
    score: 78,
    rag: "green",
    value_eur: 12_000,
    stage: "qualifying",
    contact_name: "Javier Pereira",
    contact_email: "jpereira@dataforma.gal",
    source: "referencia cliente",
    last_touched_at: "2026-04-19T11:00:00Z",
  },
  {
    id: "lead-3",
    empresa: "TechSol Asturias",
    cif: "B33991288",
    sector: "Tecnología",
    score: 85,
    rag: "green",
    value_eur: 15_000,
    stage: "meeting_exploratory",
    contact_name: "Aitor García",
    contact_email: "aitor@techsol.es",
    source: "LinkedIn",
    last_touched_at: now,
  },
  {
    id: "lead-4",
    empresa: "Consultora Moderna SL",
    cif: "B88112233",
    sector: "Servicios",
    score: 71,
    rag: "amber",
    value_eur: 9_500,
    stage: "proposal_sent",
    contact_name: "Lucía Ramos",
    contact_email: "lucia@consultoramoderna.es",
    last_touched_at: "2026-04-15T10:00:00Z",
  },
  {
    id: "lead-5",
    empresa: "Innovatech Burgos",
    cif: "B09234567",
    sector: "Tecnología",
    score: 88,
    rag: "green",
    value_eur: 18_000,
    stage: "negotiation",
    contact_name: "Miguel Ángel Soto",
    contact_email: "msoto@innovatech-burgos.com",
    last_touched_at: "2026-04-18T15:20:00Z",
  },
  {
    id: "lead-6",
    empresa: "Soluciones Digitales Levante",
    cif: "B96758412",
    sector: "Consultoría TI",
    score: 92,
    rag: "green",
    value_eur: 15_000,
    stage: "won",
    contact_name: "Clara Martínez",
    contact_email: "clara@sdlevante.es",
    last_touched_at: "2026-04-12T09:00:00Z",
  },
  {
    id: "lead-7",
    empresa: "Logística Sur SA",
    cif: "A29876543",
    sector: "Logística",
    score: 34,
    rag: "red",
    value_eur: 4_500,
    stage: "lost",
    contact_name: "Ramón Vela",
    lost_reason: "presupuesto insuficiente",
    last_touched_at: "2026-04-10T08:00:00Z",
  },
  {
    id: "lead-8",
    empresa: "Editorial Norte SL",
    cif: "B48772211",
    sector: "Editorial",
    score: 55,
    rag: "amber",
    value_eur: 6_200,
    stage: "paused",
    contact_name: "Alicia Prieto",
    last_touched_at: "2026-04-05T14:00:00Z",
  },
];
