/**
 * Legacy redirect · Sesión 3B-2B.3 Phase X.4e (architectural cleanup).
 *
 * `/admin/magic-links` (cross-cliente generation UI · 35 purposes) consolidates
 * into project-scoped `/admin/projects/[id]/auditor-handoff` (3 auditor
 * purposes only). The other 32 magic-link purposes are AUTO-generated by
 * workflow motors (M21 cliente onboarding · M05 firma documentos · M07
 * evidencia intake · m_meetings actas · 1.D.E pentest authorization · etc.)
 * and NEVER need manual Marcos generation.
 *
 * Per directive Marcos: "Magic links = SOLO auditor ENAC flow" at admin UI.
 *
 * Without a project_id resolvable from this URL (Marcos lands on /magic-links
 * without context), we redirect to /admin/projects selector · Marcos picks
 * project, then enters /admin/projects/[id]/auditor-handoff via ProjectTabs.
 *
 * Backend M12 motor unchanged · 35 purposes enum preserved (motors still use
 * the full enum internally · the admin UI surface narrows to 3 only).
 */
import { redirect } from "next/navigation";

export default function LegacyMagicLinksRedirect() {
  redirect("/admin/projects");
}
